name: lotr_api
version: 1.0.0
description: API that accesses data on quotes, characters, books, etc. from the Tolkien universe.
homepage: https://github.com/finkmoritz/lotr_api
repository: https://github.com/finkmoritz/lotr_api
issue_tracker: https://github.com/finkmoritz/lotr_api/issues
documentation: https://github.com/finkmoritz/lotr_api/blob/master/README.md

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
