name: Run tests

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Book example
        run: dart example/book_example.dart

      - name: Chapter example
        run: dart example/chapter_example.dart ${{ secrets.API_KEY }}

      - name: Character example
        run: dart example/character_example.dart ${{ secrets.API_KEY }}

      - name: Movie example
        run: dart example/movie_example.dart ${{ secrets.API_KEY }}

      - name: Quote example
        run: dart example/quote_example.dart ${{ secrets.API_KEY }}
